//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static FolderType Folder { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class FolderType() : ProjectDirectory("Folder")
{
    public folder_Level1Type folder { get; } = new();
    public partial class folder_Level1Type
    {
        public ProjectFile file_txt { get; } = new("Folder/folder/file.txt");
    }

}
}
