//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ConfigType Config { get; } = new();
        public static DataType Data { get; } = new();
        public static ValidType Valid { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class ConfigType() : ProjectDirectory("Config")
{
    public Config_Level1Type Config { get; } = new();
    public partial class Config_Level1Type
    {
        public Config_Level2Type Config { get; } = new();
        public partial class Config_Level2Type
        {
            public ProjectFile settings_xml { get; } = new("Config/Config/Config/settings.xml");
        }

    }

}
partial class DataType() : ProjectDirectory("Data")
{
    public Data_Level1Type Data { get; } = new();
    public partial class Data_Level1Type
    {
        public ProjectFile config_json { get; } = new("Data/Data/config.json");
    }

}
partial class ValidType() : ProjectDirectory("Valid")
{
    public PathType Path { get; } = new();
    public partial class PathType
    {
        public ProjectFile file_txt { get; } = new("Valid/Path/file.txt");
    }

}
}
