//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static RootType Root { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class RootType() : ProjectDirectory("Root")
{
    public Level1Type Level1 { get; } = new();
    public partial class Level1Type
    {
        public Level1_Level2Type Level1 { get; } = new();
        public partial class Level1_Level2Type
        {
            public Level2Type Level2 { get; } = new();
            public partial class Level2Type
            {
                public ProjectFile file_txt { get; } = new("Root/Level1/Level1/Level2/file.txt");
            }

        }

    }

}
}
