//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ProjectFile appsettings_json { get; } = new("appsettings.json");
        public static ProjectFile web_config { get; } = new("web.config");

        public static DataType Data { get; } = new();
        public static TemplatesType Templates { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class DataType() : ProjectDirectory("Data")
{
    public ProjectFile seed_sql { get; } = new("Data/seed.sql");
}
partial class TemplatesType() : ProjectDirectory("Templates")
{
    public ProjectFile email_html { get; } = new("Templates/email.html");
}
}
