//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ProjectFile app_settings_json { get; } = new("app.settings.json");
        public static ProjectFile web_config { get; } = new("web.config");
    }
}

namespace ProjectFilesGenerator.Types
{
}
