//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static TestType Test { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class TestType() : ProjectDirectory("Test")
{
    public Test_Level1Type Test { get; } = new();
    public partial class Test_Level1Type
    {
        public Test_Level2Type Test { get; } = new();
        public partial class Test_Level2Type
        {
            public ProjectFile data_json { get; } = new("Test/Test/Test/data.json");
        }

    }

}
}
