//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static wwwrootType wwwroot { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class wwwrootType() : ProjectDirectory("wwwroot")
{
    public assetsType assets { get; } = new();
    public partial class assetsType
    {
        public imagesType images { get; } = new();
        public partial class imagesType
        {
            public iconsType icons { get; } = new();
            public partial class iconsType
            {
                public ProjectFile home_svg { get; } = new("wwwroot/assets/images/icons/home.svg");
                public ProjectFile settings_svg { get; } = new("wwwroot/assets/images/icons/settings.svg");
            }

            public ProjectFile logo_svg { get; } = new("wwwroot/assets/images/logo.svg");
        }

        public scriptsType scripts { get; } = new();
        public partial class scriptsType
        {
            public ProjectFile app_js { get; } = new("wwwroot/assets/scripts/app.js");
        }

        public stylesType styles { get; } = new();
        public partial class stylesType
        {
            public ProjectFile main_css { get; } = new("wwwroot/assets/styles/main.css");
        }

    }

    public ProjectFile index_html { get; } = new("wwwroot/index.html");
}
}
