//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ConfigType Config { get; } = new();
        public static DataType Data { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class ConfigType() : ProjectDirectory("Config")
{
    public DevType Dev { get; } = new();
    public partial class DevType
    {
        public ProjectFile appsettings_dev_json { get; } = new("Config/Dev/appsettings.dev.json");
    }

    public ProdType Prod { get; } = new();
    public partial class ProdType
    {
        public ProjectFile appsettings_prod_json { get; } = new("Config/Prod/appsettings.prod.json");
    }

    public ProjectFile appsettings_json { get; } = new("Config/appsettings.json");
}
partial class DataType() : ProjectDirectory("Data")
{
    public ProjectFile seed_sql { get; } = new("Data/seed.sql");
}
}
