//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ProjectFile data_xml { get; } = new("data.xml");
        public static ProjectFile readme_md { get; } = new("readme.md");
        public static ProjectFile settings_yaml { get; } = new("settings.yaml");
    }
}

namespace ProjectFilesGenerator.Types
{
}
