//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ProjectDirectory ProjectDirectory { get; } = new("C:/Projects/MyApp");
        public static ProjectFile ProjectFile { get; } = new("C:/Projects/MyApp/MyApp.csproj");
        public static ProjectDirectory SolutionDirectory { get; } = new("C:/Projects/");
        public static ProjectFile SolutionFile { get; } = new("C:/Projects/MySolution.sln");

        public static ProjectFile appsettings_json { get; } = new("appsettings.json");

        public static ConfigType Config { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class ConfigType() : ProjectDirectory("Config")
{
    public ProjectFile database_json { get; } = new("Config/database.json");
}
}
