//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static Level1Type Level1 { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class Level1Type() : ProjectDirectory("Level1")
{
    public Level2Type Level2 { get; } = new();
    public partial class Level2Type
    {
        public Level3Type Level3 { get; } = new();
        public partial class Level3Type
        {
            public ProjectFile deep_txt { get; } = new("Level1/Level2/Level3/deep.txt");
        }

    }

}
}
