//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static DataType Data { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class DataType() : ProjectDirectory("Data")
{
    public ProjectFile config_json { get; } = new("Data/config.json");
}
}
