//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static DirectoryType Directory { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class DirectoryType() : ProjectDirectory("Directory")
{
    public NestedType Nested { get; } = new();
    public partial class NestedType
    {
        public Nested_Level2Type Nested { get; } = new();
        public partial class Nested_Level2Type
        {
            public ProjectFile file_txt { get; } = new("Directory/Nested/Nested/file.txt");
        }

    }

}
}
