//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ConfigType Config { get; } = new();
        public static DataType Data { get; } = new();
        public static wwwrootType wwwroot { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class ConfigType() : ProjectDirectory("Config")
{
    public ProjectFile appsettings_json { get; } = new("Config/appsettings.json");
}
partial class DataType() : ProjectDirectory("Data")
{
    public ProjectFile users_csv { get; } = new("Data/users.csv");
}
partial class wwwrootType() : ProjectDirectory("wwwroot")
{
    public ProjectFile index_html { get; } = new("wwwroot/index.html");
}
}
