//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFiles;

/// <summary>
/// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
/// </summary>
public static partial class ProjectFiles
{
    /// <summary>
    /// Files in the 'Config' directory.
    /// </summary>
    public static partial class Config
    {
        /// <summary>
        /// Path to 'appsettings.json'.
        /// </summary>
        public static string AppsettingsJson => "Config\\appsettings.json";

    }

    /// <summary>
    /// Files in the 'Data' directory.
    /// </summary>
    public static partial class Data
    {
        /// <summary>
        /// Path to 'users.csv'.
        /// </summary>
        public static string UsersCsv => "Data\\users.csv";

    }

    /// <summary>
    /// Files in the 'wwwroot' directory.
    /// </summary>
    public static partial class Wwwroot
    {
        /// <summary>
        /// Path to 'index.html'.
        /// </summary>
        public static string IndexHtml => "wwwroot\\index.html";

    }

}
