//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

using ProjectFilesGenerator.Types;

namespace ProjectFilesGenerator
{
    /// <summary>
    /// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
    /// </summary>
    public static partial class ProjectFiles
    {
        /// <summary>
        /// Files in the 'Assets' directory.
        /// </summary>
        public static Assets Assets => new();

    }
}

namespace ProjectFilesGenerator.Types
{
/// <summary>
/// Files in the 'Assets' directory.
/// </summary>
public partial class Assets
{
    public DataType Data { get; } = new();
    /// <summary>
    /// Files in the 'Data' directory.
    /// </summary>
    public partial class DataType
    {
        public string Users_csv => "Assets\\Data\\users.csv";
    }

    public ImagesType Images { get; } = new();
    /// <summary>
    /// Files in the 'Images' directory.
    /// </summary>
    public partial class ImagesType
    {
        public string Logo_png => "Assets\\Images\\logo.png";
    }

}
}
