//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFiles;

/// <summary>
/// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
/// </summary>
public static partial class ProjectFiles
{
    /// <summary>
    /// Files in the 'Configs' directory.
    /// </summary>
    public static partial class Configs
    {
        /// <summary>
        /// Path to 'appsettings.json'.
        /// </summary>
        public static string AppsettingsJson => "Configs\\appsettings.json";

        /// <summary>
        /// Path to 'database.json'.
        /// </summary>
        public static string DatabaseJson => "Configs\\database.json";

        /// <summary>
        /// Path to 'logging.json'.
        /// </summary>
        public static string LoggingJson => "Configs\\logging.json";

    }

}
