//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

using ProjectFilesGenerator.Types;

namespace ProjectFilesGenerator
{
    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static AssetsType Assets { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class AssetsType() : ProjectDirectory("Assets")
{
    public DataType Data { get; } = new();
    public partial class DataType
    {
        public ProjectFile users_csv { get; } = new("Assets/Data/users.csv");
    }

    public ImagesType Images { get; } = new();
    public partial class ImagesType
    {
        public ProjectFile logo_png { get; } = new("Assets/Images/logo.png");
    }

}
}
