//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFiles;

/// <summary>
/// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
/// </summary>
public static partial class ProjectFiles
{
    /// <summary>
    /// Path to 'included.txt'.
    /// </summary>
    public static string IncludedTxt => "included.txt";

}
