//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFiles;

/// <summary>
/// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
/// </summary>
public static partial class ProjectFiles
{
    /// <summary>
    /// Path to 'file.with.dots.txt'.
    /// </summary>
    public static string FileWithDotsTxt => "file.with.dots.txt";

    /// <summary>
    /// Path to 'my-config.json'.
    /// </summary>
    public static string MyConfigJson => "my-config.json";

    /// <summary>
    /// Path to 'user_data.csv'.
    /// </summary>
    public static string User_dataCsv => "user_data.csv";

}
