//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFiles;

/// <summary>
/// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
/// </summary>
public static partial class ProjectFiles
{
    /// <summary>
    /// Path to 'class.txt'.
    /// </summary>
    public static string @classTxt => "class.txt";

    /// <summary>
    /// Path to 'namespace.json'.
    /// </summary>
    public static string @namespaceJson => "namespace.json";

    /// <summary>
    /// Path to 'static.xml'.
    /// </summary>
    public static string @staticXml => "static.xml";

}
