//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

using ProjectFilesGenerator.Types;

namespace ProjectFilesGenerator
{
    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
    }
}

namespace ProjectFilesGenerator.Types
{
}
