//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFiles;

/// <summary>
/// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
/// </summary>
public static partial class ProjectFiles
{
    /// <summary>
    /// Files in the 'Assets' directory.
    /// </summary>
    public static partial class Assets
    {
        /// <summary>
        /// Files in the 'Data' directory.
        /// </summary>
        public static partial class Data
        {
            /// <summary>
            /// Files in the 'Config' directory.
            /// </summary>
            public static partial class Config
            {
                /// <summary>
                /// Path to 'secrets.json'.
                /// </summary>
                public static string SecretsJson => "Assets\\Data\\Config\\secrets.json";

                /// <summary>
                /// Path to 'settings.json'.
                /// </summary>
                public static string SettingsJson => "Assets\\Data\\Config\\settings.json";

            }

            /// <summary>
            /// Files in the 'Seeds' directory.
            /// </summary>
            public static partial class Seeds
            {
                /// <summary>
                /// Path to 'users.csv'.
                /// </summary>
                public static string UsersCsv => "Assets\\Data\\Seeds\\users.csv";

            }

        }

        /// <summary>
        /// Files in the 'Fonts' directory.
        /// </summary>
        public static partial class Fonts
        {
            /// <summary>
            /// Path to 'roboto.ttf'.
            /// </summary>
            public static string RobotoTtf => "Assets\\Fonts\\roboto.ttf";

        }

        /// <summary>
        /// Files in the 'Images' directory.
        /// </summary>
        public static partial class Images
        {
            /// <summary>
            /// Files in the 'Backgrounds' directory.
            /// </summary>
            public static partial class Backgrounds
            {
                /// <summary>
                /// Path to 'header.jpg'.
                /// </summary>
                public static string HeaderJpg => "Assets\\Images\\Backgrounds\\header.jpg";

            }

            /// <summary>
            /// Files in the 'Icons' directory.
            /// </summary>
            public static partial class Icons
            {
                /// <summary>
                /// Path to 'favicon.ico'.
                /// </summary>
                public static string FaviconIco => "Assets\\Images\\Icons\\favicon.ico";

                /// <summary>
                /// Path to 'logo.png'.
                /// </summary>
                public static string LogoPng => "Assets\\Images\\Icons\\logo.png";

            }

        }

        /// <summary>
        /// Path to 'readme.txt'.
        /// </summary>
        public static string ReadmeTxt => "Assets\\readme.txt";

    }

}
