//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ConfigsType Configs { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class ConfigsType() : ProjectDirectory("Configs")
{
    public ProjectFile appsettings_json { get; } = new("Configs/appsettings.json");
    public ProjectFile database_json { get; } = new("Configs/database.json");
    public ProjectFile logging_json { get; } = new("Configs/logging.json");
}
}
