//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFiles;

/// <summary>
/// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
/// </summary>
public static partial class ProjectFiles
{
    /// <summary>
    /// Files in the 'Assets' directory.
    /// </summary>
    public static partial class Assets
    {
        /// <summary>
        /// Files in the 'Data' directory.
        /// </summary>
        public static partial class Data
        {
            /// <summary>
            /// Path to 'users.csv'.
            /// </summary>
            public static string UsersCsv => "Assets\\Data\\users.csv";

        }

        /// <summary>
        /// Files in the 'Images' directory.
        /// </summary>
        public static partial class Images
        {
            /// <summary>
            /// Path to 'logo.png'.
            /// </summary>
            public static string LogoPng => "Assets\\Images\\logo.png";

        }

    }

}
