//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static AssetsType Assets { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class AssetsType() : ProjectDirectory("Assets")
{
    public DataType Data { get; } = new();
    public partial class DataType
    {
        public ConfigType Config { get; } = new();
        public partial class ConfigType
        {
            public ProjectFile secrets_json { get; } = new("Assets/Data/Config/secrets.json");
            public ProjectFile settings_json { get; } = new("Assets/Data/Config/settings.json");
        }

        public SeedsType Seeds { get; } = new();
        public partial class SeedsType
        {
            public ProjectFile users_csv { get; } = new("Assets/Data/Seeds/users.csv");
        }

    }

    public FontsType Fonts { get; } = new();
    public partial class FontsType
    {
        public ProjectFile roboto_ttf { get; } = new("Assets/Fonts/roboto.ttf");
    }

    public ImagesType Images { get; } = new();
    public partial class ImagesType
    {
        public BackgroundsType Backgrounds { get; } = new();
        public partial class BackgroundsType
        {
            public ProjectFile header_jpg { get; } = new("Assets/Images/Backgrounds/header.jpg");
        }

        public IconsType Icons { get; } = new();
        public partial class IconsType
        {
            public ProjectFile favicon_ico { get; } = new("Assets/Images/Icons/favicon.ico");
            public ProjectFile logo_png { get; } = new("Assets/Images/Icons/logo.png");
        }

    }

    public ProjectFile readme_txt { get; } = new("Assets/readme.txt");
}
}
