//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

using ProjectFilesGenerator.Types;

namespace ProjectFilesGenerator
{
    /// <summary>
    /// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
    /// </summary>
    public static partial class ProjectFiles
    {
        /// <summary>
        /// Files in the 'Configs' directory.
        /// </summary>
        public static Configs Configs => new();

    }
}

namespace ProjectFilesGenerator.Types
{
/// <summary>
/// Files in the 'Configs' directory.
/// </summary>
public partial class Configs
{
    public string Appsettings_json => "Configs\\appsettings.json";
    public string Database_json => "Configs\\database.json";
    public string Logging_json => "Configs\\logging.json";
}
}
