//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static AssetsType Assets { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class AssetsType() : ProjectDirectory("Assets")
{
    public SubDirType SubDir { get; } = new();
    public partial class SubDirType
    {
        public NestedType Nested { get; } = new();
        public partial class NestedType
        {
            public ProjectFile file3_xml { get; } = new("Assets/SubDir/Nested/file3.xml");
        }

        public ProjectFile file2_json { get; } = new("Assets/SubDir/file2.json");
    }

    public ProjectFile file1_txt { get; } = new("Assets/file1.txt");
}
}
