//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ProjectFile _1_first_txt { get; } = new("1-first.txt");
        public static ProjectFile file123_json { get; } = new("file123.json");
    }
}

namespace ProjectFilesGenerator.Types
{
}
