//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ProjectFile file_with_dots_txt { get; } = new("file.with.dots.txt");
        public static ProjectFile my_config_json { get; } = new("my-config.json");
        public static ProjectFile user_data_csv { get; } = new("user_data.csv");
    }
}

namespace ProjectFilesGenerator.Types
{
}
