//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFiles;

/// <summary>
/// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
/// </summary>
public static partial class ProjectFiles
{
    /// <summary>
    /// Path to '1-first.txt'.
    /// </summary>
    public static string _1FirstTxt => "1-first.txt";

    /// <summary>
    /// Path to 'file123.json'.
    /// </summary>
    public static string File123Json => "file123.json";

}
