// <auto-generated/>
#nullable enable

namespace ProjectFiles;

/// <summary>
/// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
/// </summary>
public static partial class ProjectFiles
{
    /// <summary>
    /// Files in the 'Config' directory.
    /// </summary>
    public static partial class Config
    {
        /// <summary>
        /// Path to 'appsettings.json'.
        /// </summary>
        public static string AppsettingsJson => "Config\\appsettings.json";

    }

    /// <summary>
    /// Files in the 'RecursiveDirectory' directory.
    /// </summary>
    public static partial class RecursiveDirectory
    {
        /// <summary>
        /// Path to 'SomeFile.txt'.
        /// </summary>
        public static string SomeFileTxt => "RecursiveDirectory\\SomeFile.txt";

        /// <summary>
        /// Files in the 'SubDir' directory.
        /// </summary>
        public static partial class SubDir
        {
            /// <summary>
            /// Path to 'NestedFile.txt'.
            /// </summary>
            public static string NestedFileTxt => "RecursiveDirectory\\SubDir\\NestedFile.txt";

        }

    }

    /// <summary>
    /// Files in the 'SpecificDirectory' directory.
    /// </summary>
    public static partial class SpecificDirectory
    {
        /// <summary>
        /// Files in the 'Dir1' directory.
        /// </summary>
        public static partial class Dir1
        {
            /// <summary>
            /// Path to 'File1.txt'.
            /// </summary>
            public static string File1Txt => "SpecificDirectory\\Dir1\\File1.txt";

            /// <summary>
            /// Path to 'File2.txt'.
            /// </summary>
            public static string File2Txt => "SpecificDirectory\\Dir1\\File2.txt";

        }

        /// <summary>
        /// Files in the 'Dir2' directory.
        /// </summary>
        public static partial class Dir2
        {
            /// <summary>
            /// Path to 'File4.txt'.
            /// </summary>
            public static string File4Txt => "SpecificDirectory\\Dir2\\File4.txt";

        }

        /// <summary>
        /// Path to 'File3.txt'.
        /// </summary>
        public static string File3Txt => "SpecificDirectory\\File3.txt";

    }

}
