namespace ProjectFiles;

[Generator]
public class Generator :
    IIncrementalGenerator
{
    static SourceText projectFileContent;
    static SourceText projectDirectoryContent;

    // static readonly DiagnosticDescriptor LogWarning = new(
    //     id: "PFSG001",
    //     title: "ProjectFiles Message",
    //     messageFormat: "{0}",
    //     category: "ProjectFiles.Generator",
    //     DiagnosticSeverity.Warning,
    //     isEnabledByDefault: true);

    static Generator()
    {
        projectFileContent = ReadResouce("ProjectFile");
        projectDirectoryContent = ReadResouce("ProjectDirectory");
    }

    static SourceText ReadResouce(string name)
    {
        var assembly = typeof(Generator).Assembly;
        using var stream = assembly.GetManifestResourceStream($"ProjectFiles.{name}.cs")!;
        using var reader = new StreamReader(stream);
        return SourceText.From(reader.ReadToEnd(), Encoding.UTF8);
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Get all additional files with CopyToOutputDirectory metadata
        var files = context.AdditionalTextsProvider
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select((pair, _) =>
            {
                var (additionalText, configOptions) = pair;

                var options = configOptions.GetOptions(additionalText);
                if (options.TryGetValue("build_metadata.AdditionalFiles.ProjectFilesGenerator", out var relativePath))
                {
                    return relativePath;
                }

                return null;
            })
            .Where(_ => !string.IsNullOrWhiteSpace(_))
            .Select((path, _) => path!)
            .Collect();

        // Generate the source
        context.RegisterSourceOutput(files, (context, files) =>
        {
            //spc.ReportDiagnostic(Diagnostic.Create(LogWarning, Location.None, "AAA"));
            var source = GenerateSource(files, context.CancellationToken);
            context.AddSource("ProjectFiles.g.cs", SourceText.From(source, Encoding.UTF8));
            context.AddSource("ProjectFiles.ProjectDirectory.g.cs", projectDirectoryContent);
            context.AddSource("ProjectFiles.ProjectFile.g.cs", projectFileContent);
        });
    }

    static string GenerateSource(ImmutableArray<string> files, Cancel cancel)
    {
        var (tree, rootFiles) = BuildFileTree(files, cancel);
        var builder = new StringBuilder();

        builder.AppendLine(
            """
            // <auto-generated/>
            #nullable enable

            namespace ProjectFilesGenerator
            {
                using ProjectFilesGenerator.Types;

                /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
                static partial class ProjectFiles
                {
            """);


        // Generate root-level file properties
        foreach (var filePath in rootFiles.OrderBy(_ => _))
        {
            cancel.ThrowIfCancellationRequested();
            var fileName = Path.GetFileName(filePath);
            var propertyName = ToFilePropertyName(fileName);
            var path = PathToCSharpString(filePath);

            builder.AppendLine($$"""        public static ProjectFile {{propertyName}} { get; } = new({{path}});""");
        }

        if (rootFiles.Count > 0 && tree.Count > 0)
        {
            builder.AppendLine();
        }

        GenerateRootProperties(builder, tree, cancel);

        builder.AppendLine(
            """
                }
            }

            namespace ProjectFilesGenerator.Types
            {
            """);

        GenerateTypeDefinitions(builder, tree, 0, cancel);

        builder.AppendLine("}");

        return builder.ToString();
    }

    static void GenerateRootProperties(StringBuilder builder, List<DirectoryNode> topLevelNodes, Cancel cancel)
    {
        foreach (var node in topLevelNodes.OrderBy(_ => _.Path))
        {
            cancel.ThrowIfCancellationRequested();

            var className = Identifier.Build(Path.GetFileName(node.Path));
            builder.AppendLine($"        public static {className}Type {className} {{ get; }} = new();");
        }
    }

    static void GenerateTypeDefinitions(StringBuilder builder, List<DirectoryNode> topLevelNodes, int indentCount, Cancel cancel)
    {
        var indent = new string(' ', indentCount * 4);

        foreach (var node in topLevelNodes.OrderBy(_ => _.Path))
        {
            cancel.ThrowIfCancellationRequested();

            var className = Identifier.Build(Path.GetFileName(node.Path));
            var pathString = PathToCSharpString(node.Path);
            builder.AppendLine(
                $$"""
                  {{indent}}partial class {{className}}Type() : ProjectDirectory({{pathString}})
                  {{indent}}{
                  """);

            // Generate file properties and subdirectory properties
            GenerateDirectoryMembers(builder, node, indentCount + 1, cancel);

            builder.AppendLine($"{indent}}}");
        }
    }

    static void GenerateDirectoryMembers(StringBuilder builder, DirectoryNode node, int indentCount, Cancel cancel)
    {
        var indent = new string(' ', indentCount * 4);

        // Generate subdirectory properties first
        foreach (var (name, childNode) in node.Directories.OrderBy(_ => _.Key))
        {
            cancel.ThrowIfCancellationRequested();

            var className = Identifier.Build(name);
            // generate subdirectory property
            builder.AppendLine($"{indent}public {className}Type {className} {{ get; }} = new();");

            // generate nested type definitions for subdirectory
            builder.AppendLine(
                $$"""
                  {{indent}}public partial class {{className}}Type
                  {{indent}}{
                  """);

            GenerateDirectoryMembers(builder, childNode, indentCount + 1, cancel);

            builder.AppendLine($"{indent}}}");
            builder.AppendLine();
        }

        // Generate file properties
        foreach (var filePath in node.Files.OrderBy(_ => _))
        {
            var fileName = Path.GetFileName(filePath);
            var propertyName = ToFilePropertyName(fileName);
            var path = PathToCSharpString(filePath);

            builder.AppendLine($$"""{{indent}}public ProjectFile {{propertyName}} { get; } = new({{path}});""");
        }
    }

    static string PathToCSharpString(string filePath)
    {
        var path = filePath.Replace("\\", "/");
        return $"\"{path}\"";
    }

    static string ToFilePropertyName(string fileName)
    {
        var nameWithoutExtension = Path.GetFileNameWithoutExtension(fileName);
        var extension = Path.GetExtension(fileName);

        var propertyName = Identifier.Build(nameWithoutExtension);

        if (!string.IsNullOrEmpty(extension))
        {
            // Remove the leading dot and make it lowercase
            var extensionWithoutDot = extension.TrimStart('.');
            propertyName += "_" + extensionWithoutDot.ToLowerInvariant();
        }

        return propertyName;
    }

    static (List<DirectoryNode> Directories, List<string> RootFiles) BuildFileTree(ImmutableArray<string> files, Cancel cancel)
    {
        var topLevelDirectories = new Dictionary<string, DirectoryNode>();
        var rootFiles = new List<string>();

        foreach (var file in files)
        {
            cancel.ThrowIfCancellationRequested();

            var parts = file.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);

            // Handle files at the root of the project
            if (parts.Length < 2)
            {
                rootFiles.Add(file);
                continue;
            }

            // Get or create top-level directory
            var topLevelName = parts[0];
            if (!topLevelDirectories.TryGetValue(topLevelName, out var topLevelNode))
            {
                topLevelNode = new()
                {
                    Path = topLevelName
                };
                topLevelDirectories[topLevelName] = topLevelNode;
            }

            var current = topLevelNode;
            var currentPath = topLevelName;

            // Navigate through middle directories
            for (var i = 1; i < parts.Length - 1; i++)
            {
                cancel.ThrowIfCancellationRequested();
                var part = parts[i];
                currentPath = currentPath + Path.DirectorySeparatorChar + part;

                if (!current.Directories.TryGetValue(part, out var child))
                {
                    child = new()
                    {
                        Path = currentPath
                    };
                    current.Directories[part] = child;
                }

                current = child;
            }

            // Add file to current directory
            current.Files.Add(file);
        }

        return (topLevelDirectories.Values.ToList(), rootFiles);
    }

    class DirectoryNode
    {
        public required string Path { get; init; }
        public Dictionary<string, DirectoryNode> Directories { get; } = [];
        public List<string> Files { get; } = [];
    }
}